# Unit = resolution of map
robot_config:
  use_sim_time: true
  x_pose: 2.0  # Initial x-coordinate (m)
  y_pose: 2.0  # Initial y-coordinate (m)
  yaw: 1.57     # Initial orientation (rad)

planner_config:
  ObstacleDilation: 1.0         # Safety margin for obstacles (m)
  WalkHeight: 0.5
  RFunctionExponent: 20.0
  Epsilon: 2.0                  # Switching function collar (m)
  VarEpsilon: 2.0
  Mu1: 0.8
  Mu2: 0.05
  WorkspaceMinX: -10.0
  WorkspaceMinY: -10.0
  WorkspaceMaxX: 20.0
  WorkspaceMaxY: 50.0
  AllowableRange: 4.0
  CutoffRange: 0.15
  SemanticMapUpdateRate: 10.0 # Hz
  LowpassCutoff: 4.0
  LowpassSampling: 25.0
  LowpassOrder: 6.0
  LowpassSamples: 10.0
  DebugFlag: False
  SimulationFlag: False # visualize path in Foxglove
  Goal_x: 8.0
  Goal_y: 15.0